/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Block list
 * OpenAPI spec version: 1.0.0
 */

export interface AccountDto {
  id: number;
  isBlockingEnabled: boolean;
  ownerId: number;
}
