/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Block list
 * OpenAPI spec version: 1.0.0
 */
import type { AddBlockItemDtoType } from "./addBlockItemDtoType";

export interface AddBlockItemDto {
  data: string;
  type: AddBlockItemDtoType;
}
