/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Block list
 * OpenAPI spec version: 1.0.0
 */

export interface SessionInfoDto {
  email: string;
  exp: number;
  iat: number;
  id: number;
}
