/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Block list
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AddBlockItemDto,
  BlockItemDto,
  BlockListControllerGetListParams,
  BlockListDto,
} from ".././models";
import { createInstance } from "../../api-instance";
import type { ErrorType, BodyType } from "../../api-instance";

export const blockListControllerGetList = (
  params?: BlockListControllerGetListParams,
  signal?: AbortSignal,
) => {
  return createInstance<BlockListDto>({
    url: `/block-list`,
    method: "get",
    params,
    signal,
  });
};

export const getBlockListControllerGetListQueryKey = (
  params?: BlockListControllerGetListParams,
) => {
  return [`/block-list`, ...(params ? [params] : [])] as const;
};

export const getBlockListControllerGetListInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof blockListControllerGetList>>,
  TError = ErrorType<unknown>,
>(
  params?: BlockListControllerGetListParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof blockListControllerGetList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBlockListControllerGetListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof blockListControllerGetList>>
  > = ({ signal }) => blockListControllerGetList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof blockListControllerGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type BlockListControllerGetListInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerGetList>>
>;
export type BlockListControllerGetListInfiniteQueryError = ErrorType<unknown>;

export const useBlockListControllerGetListInfinite = <
  TData = Awaited<ReturnType<typeof blockListControllerGetList>>,
  TError = ErrorType<unknown>,
>(
  params?: BlockListControllerGetListParams,
  options?: {
    query?: UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof blockListControllerGetList>>,
      TError,
      TData
    >;
  },
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getBlockListControllerGetListInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getBlockListControllerGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof blockListControllerGetList>>,
  TError = ErrorType<unknown>,
>(
  params?: BlockListControllerGetListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof blockListControllerGetList>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBlockListControllerGetListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof blockListControllerGetList>>
  > = ({ signal }) => blockListControllerGetList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof blockListControllerGetList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type BlockListControllerGetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerGetList>>
>;
export type BlockListControllerGetListQueryError = ErrorType<unknown>;

export const useBlockListControllerGetList = <
  TData = Awaited<ReturnType<typeof blockListControllerGetList>>,
  TError = ErrorType<unknown>,
>(
  params?: BlockListControllerGetListParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof blockListControllerGetList>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getBlockListControllerGetListQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const blockListControllerAddBlockListItem = (
  addBlockItemDto: BodyType<AddBlockItemDto>,
) => {
  return createInstance<BlockItemDto>({
    url: `/block-list/item`,
    method: "post",
    headers: { "Content-Type": "application/json" },
    data: addBlockItemDto,
  });
};

export const getBlockListControllerAddBlockListItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof blockListControllerAddBlockListItem>>,
    TError,
    { data: BodyType<AddBlockItemDto> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof blockListControllerAddBlockListItem>>,
  TError,
  { data: BodyType<AddBlockItemDto> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof blockListControllerAddBlockListItem>>,
    { data: BodyType<AddBlockItemDto> }
  > = (props) => {
    const { data } = props ?? {};

    return blockListControllerAddBlockListItem(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BlockListControllerAddBlockListItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerAddBlockListItem>>
>;
export type BlockListControllerAddBlockListItemMutationBody =
  BodyType<AddBlockItemDto>;
export type BlockListControllerAddBlockListItemMutationError =
  ErrorType<unknown>;

export const useBlockListControllerAddBlockListItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof blockListControllerAddBlockListItem>>,
    TError,
    { data: BodyType<AddBlockItemDto> },
    TContext
  >;
}) => {
  const mutationOptions =
    getBlockListControllerAddBlockListItemMutationOptions(options);

  return useMutation(mutationOptions);
};
export const blockListControllerRemoveBlockItem = (id: number) => {
  return createInstance<BlockItemDto>({
    url: `/block-list/item/${id}`,
    method: "delete",
  });
};

export const getBlockListControllerRemoveBlockItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>,
  TError,
  { id: number },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return blockListControllerRemoveBlockItem(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type BlockListControllerRemoveBlockItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>
>;

export type BlockListControllerRemoveBlockItemMutationError =
  ErrorType<unknown>;

export const useBlockListControllerRemoveBlockItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>,
    TError,
    { id: number },
    TContext
  >;
}) => {
  const mutationOptions =
    getBlockListControllerRemoveBlockItemMutationOptions(options);

  return useMutation(mutationOptions);
};
