/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Block list
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { SessionInfoDto, SignInBodyDto, SignUpBodyDto } from ".././models";
import { createInstance } from "../../api-instance";
import type { ErrorType, BodyType } from "../../api-instance";

export const authControllerSignUp = (
  signUpBodyDto: BodyType<SignUpBodyDto>,
) => {
  return createInstance<void>({
    url: `/auth/sign-up`,
    method: "post",
    headers: { "Content-Type": "application/json" },
    data: signUpBodyDto,
  });
};

export const getAuthControllerSignUpMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    TError,
    { data: BodyType<SignUpBodyDto> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignUp>>,
  TError,
  { data: BodyType<SignUpBodyDto> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    { data: BodyType<SignUpBodyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignUp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignUpMutationBody = BodyType<SignUpBodyDto>;
export type AuthControllerSignUpMutationError = ErrorType<unknown>;

export const useAuthControllerSignUp = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    TError,
    { data: BodyType<SignUpBodyDto> },
    TContext
  >;
}) => {
  const mutationOptions = getAuthControllerSignUpMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authControllerSignIn = (
  signInBodyDto: BodyType<SignInBodyDto>,
) => {
  return createInstance<void>({
    url: `/auth/sign-in`,
    method: "post",
    headers: { "Content-Type": "application/json" },
    data: signInBodyDto,
  });
};

export const getAuthControllerSignInMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    TError,
    { data: BodyType<SignInBodyDto> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignIn>>,
  TError,
  { data: BodyType<SignInBodyDto> },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    { data: BodyType<SignInBodyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignIn(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignInMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignInMutationBody = BodyType<SignInBodyDto>;
export type AuthControllerSignInMutationError = ErrorType<unknown>;

export const useAuthControllerSignIn = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    TError,
    { data: BodyType<SignInBodyDto> },
    TContext
  >;
}) => {
  const mutationOptions = getAuthControllerSignInMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authControllerSignOut = () => {
  return createInstance<void>({ url: `/auth/sign-out`, method: "post" });
};

export const getAuthControllerSignOutMutationOptions = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignOut>>,
    TError,
    TVariables,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignOut>>,
  TError,
  TVariables,
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignOut>>,
    TVariables
  > = () => {
    return authControllerSignOut();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignOutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;

export type AuthControllerSignOutMutationError = ErrorType<unknown>;

export const useAuthControllerSignOut = <
  TError = ErrorType<unknown>,
  TVariables = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignOut>>,
    TError,
    TVariables,
    TContext
  >;
}) => {
  const mutationOptions = getAuthControllerSignOutMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authControllerGetSessionInfo = (signal?: AbortSignal) => {
  return createInstance<SessionInfoDto>({
    url: `/auth/session`,
    method: "get",
    signal,
  });
};

export const getAuthControllerGetSessionInfoQueryKey = () => {
  return [`/auth/session`] as const;
};

export const getAuthControllerGetSessionInfoInfiniteQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetSessionInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>
  > = ({ signal }) => authControllerGetSessionInfo(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGetSessionInfoInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
export type AuthControllerGetSessionInfoInfiniteQueryError = ErrorType<unknown>;

export const useAuthControllerGetSessionInfoInfinite = <
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  >;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getAuthControllerGetSessionInfoInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAuthControllerGetSessionInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetSessionInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>
  > = ({ signal }) => authControllerGetSessionInfo(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthControllerGetSessionInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
export type AuthControllerGetSessionInfoQueryError = ErrorType<unknown>;

export const useAuthControllerGetSessionInfo = <
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAuthControllerGetSessionInfoQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
